services:
  nextjs:
    build: .
    container_name: nextjs
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always
  inventory-application:
    build:
      context: ../inventory-application
    container_name: inventory-application
    ports:
      - "3000:3000"
    restart: always
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../ssl:/etc/nginx/ssl:ro
    restart: always
    depends_on:
      - nextjs, inventory-application
