services:
  nextjs:
    build: .
    container_name: nextjs
    environment:
      - NODE_ENV=production
    restart: always
  inventory-application:
    build:
      context: ../inventory-application
    container_name: inventory-application
    environment:
      MONGOOSE_PASS: ${MONGOOSE_PASS}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      CONTACT_EMAIL: ${CONTACT_EMAIL}
    restart: always
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
      - "3001:3001"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../ssl:/etc/nginx/ssl:ro
    restart: always
    depends_on:
      - nextjs
      - inventory-application
