services:
  nextjs:
    image: peterhellmuth/portfolio-nextjs:latest
    container_name: nextjs
    restart: always
  inventory-application:
    image: peterhellmuth/portfolio-inventory-application:latest
    container_name: inventory-application
    environment:
      MONGOOSE_PASS: ${MONGOOSE_PASS}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      CONTACT_EMAIL: ${CONTACT_EMAIL}
    restart: always
  nginx:
    image: peterhellmuth/portfolio-nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
      - "3001:3001"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../ssl:/etc/nginx/ssl:ro
    restart: always
