# nginx/Dockerfile

# Use the official Nginx image from Docker Hub
FROM nginx:latest

# Copy the custom nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Expose ports 80 and 443
EXPOSE 80
EXPOSE 443

# Start nginx when the container starts
CMD ["nginx", "-g", "daemon off;"]