FROM nginx:1.23.3-alpine

# Copy the nginx.conf from the current directory (where the Dockerfile is) to the nginx configuration directory
COPY nginx.conf /etc/nginx/nginx.conf

# Expose the necessary ports
EXPOSE 80
EXPOSE 443