name: Deploy latest docker images on server

on:
  # Triggers the workflow on push request events but only for the main branch
  pull_request_target:
    branches:
      - main
    types:
      - closed

jobs:
  deploy_image:
    name: Update images and config on EC2 instance
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy Docker Compose file to server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "~/deploy/"

      - name: Copy Nginx config file to server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "./nginx/nginx.conf"
          target: "~/deploy/nginx/"

      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/deploy
            sudo docker compose pull
            sudo docker compose up -d --remove-orphans
